# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ThinkBetter < Formula
  desc "Structured decision-making and problem-solving skills for AI coding assistants"
  homepage "https://thinkbetter.dev/"
  version "1.5.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/HoangTheQuyen/think-better/releases/download/v1.5.0/think-better_1.5.0_darwin_amd64.tar.gz"
      sha256 "d81d0def495cc68c3244984b17eca40ef7a44d268a5df221abd733e83a2624c8"

      define_method(:install) do
        bin.install "think-better"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/HoangTheQuyen/think-better/releases/download/v1.5.0/think-better_1.5.0_darwin_arm64.tar.gz"
      sha256 "c88e6f2867b1758c27169262c9a55050b2a18baf869b51897fd9d47dc03bfbb2"

      define_method(:install) do
        bin.install "think-better"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/HoangTheQuyen/think-better/releases/download/v1.5.0/think-better_1.5.0_linux_amd64.tar.gz"
      sha256 "bc64016ff89d90b07c35da90c4a4822ea7f627dbc2b6fa295fae4c890ba13daa"
      define_method(:install) do
        bin.install "think-better"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/HoangTheQuyen/think-better/releases/download/v1.5.0/think-better_1.5.0_linux_arm64.tar.gz"
      sha256 "82873aef9cc11ebe87c11633af034b464b8227b5d32d8b85a9b8bf57d8442e51"
      define_method(:install) do
        bin.install "think-better"
      end
    end
  end

  def caveats
    <<~EOS
      Install skills in your project with:
        think-better init --ai claude   # or: copilot, antigravity, opencode
      The skill scripts need Python 3 (check with: think-better check).
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/think-better version")
  end
end
