# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ThinkBetter < Formula
  desc "Structured decision-making and problem-solving skills for AI coding assistants"
  homepage "https://thinkbetter.dev/"
  version "1.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/HoangTheQuyen/think-better/releases/download/v1.1.0/think-better_1.1.0_darwin_amd64.tar.gz"
      sha256 "be1072cde56fc69c3ab37337779df12be49553be4454161d4c9863a0381d5502"

      define_method(:install) do
        bin.install "think-better"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/HoangTheQuyen/think-better/releases/download/v1.1.0/think-better_1.1.0_darwin_arm64.tar.gz"
      sha256 "ca83c6716e4edfc57a9f6840eebd9a5a711eaeab538dc2ed9511335d32c92378"

      define_method(:install) do
        bin.install "think-better"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/HoangTheQuyen/think-better/releases/download/v1.1.0/think-better_1.1.0_linux_amd64.tar.gz"
      sha256 "49459cc4f0ea5b4384b256a0d2330cf91331b34304aa31f80f84e8ec37434778"
      define_method(:install) do
        bin.install "think-better"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/HoangTheQuyen/think-better/releases/download/v1.1.0/think-better_1.1.0_linux_arm64.tar.gz"
      sha256 "33c7d150faeb90003dc998b2c779e4072e8026439047fd11a6970531024ebf4a"
      define_method(:install) do
        bin.install "think-better"
      end
    end
  end

  def caveats
    <<~EOS
      Install skills in your project with:
        think-better init --ai claude   # or: copilot, antigravity, opencode
      The skill scripts need Python 3 (check with: think-better check).
    EOS
  end

  test do
    system "#{bin}/think-better", "version"
  end
end
