# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ThinkBetter < Formula
  desc "Structured decision-making and problem-solving skills for AI coding assistants"
  homepage "https://thinkbetter.dev/"
  version "1.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/HoangTheQuyen/think-better/releases/download/v1.3.0/think-better_1.3.0_darwin_amd64.tar.gz"
      sha256 "ea70cd359c7472d21bfaa179a5646cfeb55d1b61c63652a06f739395f363a73d"

      define_method(:install) do
        bin.install "think-better"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/HoangTheQuyen/think-better/releases/download/v1.3.0/think-better_1.3.0_darwin_arm64.tar.gz"
      sha256 "308d8686f404a6cd997119f71fcf7fb12a0ae3a3d67cc6802652adcab0342e48"

      define_method(:install) do
        bin.install "think-better"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/HoangTheQuyen/think-better/releases/download/v1.3.0/think-better_1.3.0_linux_amd64.tar.gz"
      sha256 "7cc7c0cab5aeed358d7ac5117eb5764d0ca0957d9f1f2927f5fe429a73c1814e"
      define_method(:install) do
        bin.install "think-better"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/HoangTheQuyen/think-better/releases/download/v1.3.0/think-better_1.3.0_linux_arm64.tar.gz"
      sha256 "e33158c0a49858105b32be661d4960cbe2f5ff4ba736b21efdc20ee2a9146a6a"
      define_method(:install) do
        bin.install "think-better"
      end
    end
  end

  def caveats
    <<~EOS
      Install skills in your project with:
        think-better init --ai claude   # or: copilot, antigravity, opencode
      The skill scripts need Python 3 (check with: think-better check).
    EOS
  end

  test do
    system "#{bin}/think-better", "version"
  end
end
